/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.ultimateMicr.Sdk {

public enum ULTMICR_SDK_IMAGE_TYPE {
  ULTMICR_SDK_IMAGE_TYPE_RGB24,
  ULTMICR_SDK_IMAGE_TYPE_RGBA32,
  ULTMICR_SDK_IMAGE_TYPE_BGRA32,
  ULTMICR_SDK_IMAGE_TYPE_NV12,
  ULTMICR_SDK_IMAGE_TYPE_NV21,
  ULTMICR_SDK_IMAGE_TYPE_YUV420P,
  ULTMICR_SDK_IMAGE_TYPE_YVU420P,
  ULTMICR_SDK_IMAGE_TYPE_YUV422P,
  ULTMICR_SDK_IMAGE_TYPE_YUV444P
}

}
