/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.ultimateMicr.Sdk {

using System;
using System.Runtime.InteropServices;

public class UltMicrSdkEngine : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UltMicrSdkEngine(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(UltMicrSdkEngine obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~UltMicrSdkEngine() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ultimateMicrSdkPINVOKE.delete_UltMicrSdkEngine(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public static UltMicrSdkResult init(string jsonConfig) {
    UltMicrSdkResult ret = new UltMicrSdkResult(ultimateMicrSdkPINVOKE.UltMicrSdkEngine_init__SWIG_0(jsonConfig), true);
    return ret;
  }

  public static UltMicrSdkResult init() {
    UltMicrSdkResult ret = new UltMicrSdkResult(ultimateMicrSdkPINVOKE.UltMicrSdkEngine_init__SWIG_1(), true);
    return ret;
  }

  public static UltMicrSdkResult deInit() {
    UltMicrSdkResult ret = new UltMicrSdkResult(ultimateMicrSdkPINVOKE.UltMicrSdkEngine_deInit(), true);
    return ret;
  }

  public static UltMicrSdkResult process(ULTMICR_SDK_IMAGE_TYPE imageType, IntPtr imageData, uint imageWidthInSamples, uint imageHeightInSamples, uint imageStrideInSamples, int imageExifOrientation) {
    UltMicrSdkResult ret = new UltMicrSdkResult(ultimateMicrSdkPINVOKE.UltMicrSdkEngine_process__SWIG_0((int)imageType, imageData, imageWidthInSamples, imageHeightInSamples, imageStrideInSamples, imageExifOrientation), true);
    return ret;
  }

  public static UltMicrSdkResult process(ULTMICR_SDK_IMAGE_TYPE imageType, IntPtr imageData, uint imageWidthInSamples, uint imageHeightInSamples, uint imageStrideInSamples) {
    UltMicrSdkResult ret = new UltMicrSdkResult(ultimateMicrSdkPINVOKE.UltMicrSdkEngine_process__SWIG_1((int)imageType, imageData, imageWidthInSamples, imageHeightInSamples, imageStrideInSamples), true);
    return ret;
  }

  public static UltMicrSdkResult process(ULTMICR_SDK_IMAGE_TYPE imageType, IntPtr imageData, uint imageWidthInSamples, uint imageHeightInSamples) {
    UltMicrSdkResult ret = new UltMicrSdkResult(ultimateMicrSdkPINVOKE.UltMicrSdkEngine_process__SWIG_2((int)imageType, imageData, imageWidthInSamples, imageHeightInSamples), true);
    return ret;
  }

  public static UltMicrSdkResult process(ULTMICR_SDK_IMAGE_TYPE imageType, IntPtr yPtr, IntPtr uPtr, IntPtr vPtr, uint widthInSamples, uint heightInSamples, uint yStrideInBytes, uint uStrideInBytes, uint vStrideInBytes, uint uvPixelStrideInBytes, int exifOrientation) {
    UltMicrSdkResult ret = new UltMicrSdkResult(ultimateMicrSdkPINVOKE.UltMicrSdkEngine_process__SWIG_3((int)imageType, yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes, uvPixelStrideInBytes, exifOrientation), true);
    return ret;
  }

  public static UltMicrSdkResult process(ULTMICR_SDK_IMAGE_TYPE imageType, IntPtr yPtr, IntPtr uPtr, IntPtr vPtr, uint widthInSamples, uint heightInSamples, uint yStrideInBytes, uint uStrideInBytes, uint vStrideInBytes, uint uvPixelStrideInBytes) {
    UltMicrSdkResult ret = new UltMicrSdkResult(ultimateMicrSdkPINVOKE.UltMicrSdkEngine_process__SWIG_4((int)imageType, yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes, uvPixelStrideInBytes), true);
    return ret;
  }

  public static UltMicrSdkResult process(ULTMICR_SDK_IMAGE_TYPE imageType, IntPtr yPtr, IntPtr uPtr, IntPtr vPtr, uint widthInSamples, uint heightInSamples, uint yStrideInBytes, uint uStrideInBytes, uint vStrideInBytes) {
    UltMicrSdkResult ret = new UltMicrSdkResult(ultimateMicrSdkPINVOKE.UltMicrSdkEngine_process__SWIG_5((int)imageType, yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes), true);
    return ret;
  }

  public static UltMicrSdkResult requestRuntimeLicenseKey(bool rawInsteadOfJSON) {
    UltMicrSdkResult ret = new UltMicrSdkResult(ultimateMicrSdkPINVOKE.UltMicrSdkEngine_requestRuntimeLicenseKey__SWIG_0(rawInsteadOfJSON), true);
    return ret;
  }

  public static UltMicrSdkResult requestRuntimeLicenseKey() {
    UltMicrSdkResult ret = new UltMicrSdkResult(ultimateMicrSdkPINVOKE.UltMicrSdkEngine_requestRuntimeLicenseKey__SWIG_1(), true);
    return ret;
  }

  public static UltMicrSdkResult warmUp(ULTMICR_SDK_IMAGE_TYPE imageType) {
    UltMicrSdkResult ret = new UltMicrSdkResult(ultimateMicrSdkPINVOKE.UltMicrSdkEngine_warmUp((int)imageType), true);
    return ret;
  }

}

}
