/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.ultimateMicr.Sdk;

public class ultimateMicrSdkJNI {
  public final static native long new_UltMicrSdkResult__SWIG_0();
  public final static native long new_UltMicrSdkResult__SWIG_1(int jarg1, String jarg2, String jarg3, long jarg4);
  public final static native long new_UltMicrSdkResult__SWIG_2(int jarg1, String jarg2, String jarg3);
  public final static native long new_UltMicrSdkResult__SWIG_3(long jarg1, UltMicrSdkResult jarg1_);
  public final static native void delete_UltMicrSdkResult(long jarg1);
  public final static native int UltMicrSdkResult_code(long jarg1, UltMicrSdkResult jarg1_);
  public final static native String UltMicrSdkResult_phrase(long jarg1, UltMicrSdkResult jarg1_);
  public final static native String UltMicrSdkResult_json(long jarg1, UltMicrSdkResult jarg1_);
  public final static native long UltMicrSdkResult_numZones(long jarg1, UltMicrSdkResult jarg1_);
  public final static native boolean UltMicrSdkResult_isOK(long jarg1, UltMicrSdkResult jarg1_);
  public final static native long UltMicrSdkEngine_init__SWIG_0(String jarg1);
  public final static native long UltMicrSdkEngine_init__SWIG_1();
  public final static native long UltMicrSdkEngine_deInit();
  public final static native long UltMicrSdkEngine_process__SWIG_0(int jarg1, java.nio.ByteBuffer jarg2, long jarg3, long jarg4, long jarg5, int jarg6);
  public final static native long UltMicrSdkEngine_process__SWIG_1(int jarg1, java.nio.ByteBuffer jarg2, long jarg3, long jarg4, long jarg5);
  public final static native long UltMicrSdkEngine_process__SWIG_2(int jarg1, java.nio.ByteBuffer jarg2, long jarg3, long jarg4);
  public final static native long UltMicrSdkEngine_process__SWIG_3(int jarg1, java.nio.ByteBuffer jarg2, java.nio.ByteBuffer jarg3, java.nio.ByteBuffer jarg4, long jarg5, long jarg6, long jarg7, long jarg8, long jarg9, long jarg10, int jarg11);
  public final static native long UltMicrSdkEngine_process__SWIG_4(int jarg1, java.nio.ByteBuffer jarg2, java.nio.ByteBuffer jarg3, java.nio.ByteBuffer jarg4, long jarg5, long jarg6, long jarg7, long jarg8, long jarg9, long jarg10);
  public final static native long UltMicrSdkEngine_process__SWIG_5(int jarg1, java.nio.ByteBuffer jarg2, java.nio.ByteBuffer jarg3, java.nio.ByteBuffer jarg4, long jarg5, long jarg6, long jarg7, long jarg8, long jarg9);
  public final static native int UltMicrSdkEngine_exifOrientation(java.nio.ByteBuffer jarg1, long jarg2);
  public final static native long UltMicrSdkEngine_requestRuntimeLicenseKey__SWIG_0(boolean jarg1);
  public final static native long UltMicrSdkEngine_requestRuntimeLicenseKey__SWIG_1();
  public final static native long UltMicrSdkEngine_warmUp(int jarg1);
  public final static native void delete_UltMicrSdkEngine(long jarg1);
}
