/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.ultimateMicr.Sdk;

public class UltMicrSdkResult {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UltMicrSdkResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UltMicrSdkResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ultimateMicrSdkJNI.delete_UltMicrSdkResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UltMicrSdkResult() {
    this(ultimateMicrSdkJNI.new_UltMicrSdkResult__SWIG_0(), true);
  }

  public UltMicrSdkResult(int code, String phrase, String json, long numZones) {
    this(ultimateMicrSdkJNI.new_UltMicrSdkResult__SWIG_1(code, phrase, json, numZones), true);
  }

  public UltMicrSdkResult(int code, String phrase, String json) {
    this(ultimateMicrSdkJNI.new_UltMicrSdkResult__SWIG_2(code, phrase, json), true);
  }

  public UltMicrSdkResult(UltMicrSdkResult other) {
    this(ultimateMicrSdkJNI.new_UltMicrSdkResult__SWIG_3(UltMicrSdkResult.getCPtr(other), other), true);
  }

  public int code() {
    return ultimateMicrSdkJNI.UltMicrSdkResult_code(swigCPtr, this);
  }

  public String phrase() {
    return ultimateMicrSdkJNI.UltMicrSdkResult_phrase(swigCPtr, this);
  }

  public String json() {
    return ultimateMicrSdkJNI.UltMicrSdkResult_json(swigCPtr, this);
  }

  public long numZones() {
    return ultimateMicrSdkJNI.UltMicrSdkResult_numZones(swigCPtr, this);
  }

  public boolean isOK() {
    return ultimateMicrSdkJNI.UltMicrSdkResult_isOK(swigCPtr, this);
  }

}
