/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.ultimateMicr.Sdk;

public class UltMicrSdkEngine {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UltMicrSdkEngine(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UltMicrSdkEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ultimateMicrSdkJNI.delete_UltMicrSdkEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static UltMicrSdkResult init(String jsonConfig) {
    return new UltMicrSdkResult(ultimateMicrSdkJNI.UltMicrSdkEngine_init__SWIG_0(jsonConfig), true);
  }

  public static UltMicrSdkResult init() {
    return new UltMicrSdkResult(ultimateMicrSdkJNI.UltMicrSdkEngine_init__SWIG_1(), true);
  }

  public static UltMicrSdkResult deInit() {
    return new UltMicrSdkResult(ultimateMicrSdkJNI.UltMicrSdkEngine_deInit(), true);
  }

  public static UltMicrSdkResult process(ULTMICR_SDK_IMAGE_TYPE imageType, java.nio.ByteBuffer imageData, long imageWidthInSamples, long imageHeightInSamples, long imageStrideInSamples, int imageExifOrientation) {
    return new UltMicrSdkResult(ultimateMicrSdkJNI.UltMicrSdkEngine_process__SWIG_0(imageType.swigValue(), imageData, imageWidthInSamples, imageHeightInSamples, imageStrideInSamples, imageExifOrientation), true);
  }

  public static UltMicrSdkResult process(ULTMICR_SDK_IMAGE_TYPE imageType, java.nio.ByteBuffer imageData, long imageWidthInSamples, long imageHeightInSamples, long imageStrideInSamples) {
    return new UltMicrSdkResult(ultimateMicrSdkJNI.UltMicrSdkEngine_process__SWIG_1(imageType.swigValue(), imageData, imageWidthInSamples, imageHeightInSamples, imageStrideInSamples), true);
  }

  public static UltMicrSdkResult process(ULTMICR_SDK_IMAGE_TYPE imageType, java.nio.ByteBuffer imageData, long imageWidthInSamples, long imageHeightInSamples) {
    return new UltMicrSdkResult(ultimateMicrSdkJNI.UltMicrSdkEngine_process__SWIG_2(imageType.swigValue(), imageData, imageWidthInSamples, imageHeightInSamples), true);
  }

  public static UltMicrSdkResult process(ULTMICR_SDK_IMAGE_TYPE imageType, java.nio.ByteBuffer yPtr, java.nio.ByteBuffer uPtr, java.nio.ByteBuffer vPtr, long widthInSamples, long heightInSamples, long yStrideInBytes, long uStrideInBytes, long vStrideInBytes, long uvPixelStrideInBytes, int exifOrientation) {
    return new UltMicrSdkResult(ultimateMicrSdkJNI.UltMicrSdkEngine_process__SWIG_3(imageType.swigValue(), yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes, uvPixelStrideInBytes, exifOrientation), true);
  }

  public static UltMicrSdkResult process(ULTMICR_SDK_IMAGE_TYPE imageType, java.nio.ByteBuffer yPtr, java.nio.ByteBuffer uPtr, java.nio.ByteBuffer vPtr, long widthInSamples, long heightInSamples, long yStrideInBytes, long uStrideInBytes, long vStrideInBytes, long uvPixelStrideInBytes) {
    return new UltMicrSdkResult(ultimateMicrSdkJNI.UltMicrSdkEngine_process__SWIG_4(imageType.swigValue(), yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes, uvPixelStrideInBytes), true);
  }

  public static UltMicrSdkResult process(ULTMICR_SDK_IMAGE_TYPE imageType, java.nio.ByteBuffer yPtr, java.nio.ByteBuffer uPtr, java.nio.ByteBuffer vPtr, long widthInSamples, long heightInSamples, long yStrideInBytes, long uStrideInBytes, long vStrideInBytes) {
    return new UltMicrSdkResult(ultimateMicrSdkJNI.UltMicrSdkEngine_process__SWIG_5(imageType.swigValue(), yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes), true);
  }

  public static UltMicrSdkResult requestRuntimeLicenseKey(boolean rawInsteadOfJSON) {
    return new UltMicrSdkResult(ultimateMicrSdkJNI.UltMicrSdkEngine_requestRuntimeLicenseKey__SWIG_0(rawInsteadOfJSON), true);
  }

  public static UltMicrSdkResult requestRuntimeLicenseKey() {
    return new UltMicrSdkResult(ultimateMicrSdkJNI.UltMicrSdkEngine_requestRuntimeLicenseKey__SWIG_1(), true);
  }

  public static UltMicrSdkResult warmUp(ULTMICR_SDK_IMAGE_TYPE imageType) {
    return new UltMicrSdkResult(ultimateMicrSdkJNI.UltMicrSdkEngine_warmUp(imageType.swigValue()), true);
  }

}
